RDFvevo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^', include('inasistencias.urls', namespace = "inasistencias")),
    url(r'^admin/', include(admin.site.urls)),
)

inasistencias/urls.py
from django.conf.urls import patterns, include, url
from RDFvevo import settings

urlpatterns = patterns('',

    url(r'^$', 'inasistencias.views.home', name='home'),
    url(r'^loguearse/$', 'inasistencias.views.loguearse', name='loguearse'),
    url(r'^desloguearse/$', 'inasistencias.views.desloguearse', name='desloguearse'),
    url(r'^curso/(?P<id_curso>\d+)/$', 'inasistencias.views.curso', name='curso'),
    url(r'^curso/(?P<id_curso>\d+)/info/$', 'inasistencias.views.info', name='info'),
    url(r'^alumno/(?P<id_alumno>\d+)/$', 'inasistencias.views.alumno', name='alumno'),
    
)

inasistencias/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext
from django.template.defaulttags import NowNode
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.decorators import login_required

from inasistencias.templatetags.faltas import formatear_fecha
from inasistencias.models import Curso, Preceptor, Alumno, Curso, Inasistencia, Observacion, Amonestacion


@login_required(login_url="/loguearse")
def home(request):
    context = RequestContext(request)
    
    # Si es Administrador
    if request.user.is_staff:

	if request.method == 'POST':
	    print request.POST
	    
	    if 'infoCurso' in request.POST:
		curso = request.POST['cursos']
		print Curso.objects.filter(id=curso)
		
		return HttpResponseRedirect(reverse('inasistencias:info', args=(int(curso), ) ))
	      
	    elif 'nuevoCurso' in request.POST:
		return HttpResponseRedirect('admin/inasistencias/curso/add/')
		
	    elif 'verPreceptor' in request.POST:
		preceptor = request.POST['preceptores']
		return HttpResponseRedirect('admin/inasistencias/preceptor/' + preceptor + '/')
		
	    elif 'nuevoPreceptor' in request.POST:
		return HttpResponseRedirect('admin/inasistencias/preceptor/add/')
	      
	return render_to_response('admin/administrador.html', {'usuario': request.user, 'cursos': Curso.objects.all(), 'preceptores': Preceptor.objects.all()}, context)
	
    
    # Si es Preceptor
    elif es_preceptor(request.user):
	return render_to_response('preceptor/preceptor.html', {'usuario': request.user, 'cursos': Curso.objects.all().filter(preceptor=request.user)}, context)
    
    # Si es Alumno
    elif es_alumno(request.user):
	return render_to_response('alumno/alumno.html', {'usuario': request.user, 'alumno': Alumno.objects.get(pk=request.user.pk) }, context)
    
    # Sino
    else:
	return HttpResponse('ERROR')

def loguearse(request):
    context = RequestContext(request)
	
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
	# Usuario y contrasena
	username = request.POST['username']
	password = request.POST['password']

	user = authenticate(username=username, password=password)

	if user:
	    # Is the account active? It could have been disabled.
	    if user.is_active:
		# If the account is valid and active, we can log the user in.
		# We'll send the user back to the homepage.
		login(request, user)

		return redirect('/')

	    else:
		# An inactive account was used - no logging in!
		return HttpResponse("ERROR: cuenta inactiva.")
	else:
	    # Bad login details were provided. So we can't log the user in.
	    print "Invalid login details: {0}, {1}".format(username, password)
	    return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
	# No context variables to pass to the template system, hence the
	# blank dictionary object...
	
	return render_to_response('login.html', context)

def desloguearse(request):
    logout(request)
    
    return redirect('/loguearse')

@login_required(login_url="/loguearse")
def curso(request, id_curso):
    fecha = NowNode("SHORT_DATE_FORMAT").render(None)
    alumnos = Alumno.objects.all().filter(curso_id=id_curso)
    cambios = False
    
    if request.method == 'POST':
	
	if request.POST.get('cargar'):
	    fecha = request.POST['fecha']
	
	if request.POST.get('guardar'):
	    fecha = request.POST['fecha']
	    preceptor = request.POST['preceptor']
	    
	    registrar_faltas(fecha, alumnos, request.POST, preceptor)
	    cambios = True
		
    
    # Si es preceptor
    if es_preceptor(request.user):
	return render_to_response('preceptor/curso.html', {'usuario': request.user, 'cambios':cambios, 'alumnos': alumnos, 'curso': Curso.objects.get(id=id_curso), 'dia': fecha}, RequestContext(request))

    # Sino
    else:
	return HttpResponse('Necesitas estar logueado como preceptor para ver esto...')

@login_required(login_url="/loguearse")
def alumno(request, id_alumno):
    faltas = Inasistencia.objects.all().filter(alumno_id=id_alumno)
    cambios = False
    
    # Si es preceptor
    if es_preceptor(request.user):
      
	# Si se ha recibido una peticion "POST"
        if request.method == 'POST':
	    print request.POST
	    
	    # Si es una peticion de "Guardar faltas"    
            if 'guardarFaltas' in request.POST:
		guardarFaltas(faltas, request.POST)
		cambios = True

            # Si es una peticion de "Crear Observacion"    
            if request.POST.get('motivoObservacion'):
                fecha = request.POST.get('fechaObservacion')
                fecha2 = formatear_fecha(fecha)
                motivo = request.POST['motivoObservacion']
                alumno = Alumno.objects.get(id=id_alumno)
                preceptor = request.POST['preceptor']
                preceptor = Preceptor.objects.get(id=preceptor)
                observar(alumno, fecha2, motivo, preceptor)
                cambios = True

            # Si es una peticion de "Crear Amonestacion"
            if request.POST.get('motivoAmonestacion'):
		print request.POST
                fecha = request.POST.get('fechaAmonestacion')
                fecha2 = formatear_fecha(fecha)
                motivo = request.POST['motivoAmonestacion']
                cantidad = request.POST['cantAmonestacion']
                alumno = Alumno.objects.get(id=id_alumno)
                preceptor = request.POST['preceptor']
                preceptor = Preceptor.objects.get(id=preceptor)
                amonestar(alumno, fecha2, motivo, cantidad, preceptor)
                cambios = True

            # Si es una peticion de "Reincorporar"
            if request.POST.get('alumnoReincorporacion'):
                alumno = Alumno.objects.get(id=id_alumno)
                reincorporar(alumno)
                cambios = True
	
	return render_to_response('preceptor/alumno.html', {'usuario': request.user, 'cambios': cambios, 'alumno': Alumno.objects.get(id=id_alumno)}, RequestContext(request))

    # Sino
    else:
	return HttpResponse('Necesitas estar logueado como preceptor para ver esto...')

@login_required(login_url="/loguearse")
def info(request, id_curso):
    print request.POST
    # Si es preceptor o administrador
    if es_preceptor(request.user) or request.user.is_staff:
	return render_to_response('preceptor/info.html', {'usuario': request.user, 'curso': Curso.objects.get(id=id_curso)}, RequestContext(request))

    # Sino
    else:
	return HttpResponse('Necesitas estar logueado como preceptor para ver esto...')


# Devuelve true si es preceptor
def es_preceptor(usuario):
    try:
	Preceptor.objects.get(pk=usuario.pk)
	return True
    except:
	return False

# Devuelve true si es alumno
def es_alumno(usuario):
    try:
	Alumno.objects.get(pk=usuario.pk)
	return True
    except:
	return False

# Leva a cabo el registro de faltas de una lista de alumnos
def registrar_faltas(fecha, alumnos, post, preceptor):
    fecha = formatear_fecha(fecha)
    dic = {
      'P': 0,
      '1/2': 0.5,
      '1/4': 0.25,
      '3/4': 0.75,
      'A': 1,
    }

    for al in alumnos:
	falta = Inasistencia.objects.filter(alumno=al).filter(fecha=fecha)
	# Tipo de inasistencia
	tipo = post[str(al.id)]
	
	# Si existe una falta de ese alumno en esa fecha
	if falta:
	    # Si no coincide
	    if dic[tipo] != falta[0].tipo:
		falta[0].tipo = dic[tipo]
		falta[0].save()
	
	# Si no existe una falta de ese alumno en esa fecha se crea
	else:
	    fal = Inasistencia(tipo=dic[tipo], alumno=al, preceptor=Preceptor.objects.get(username=preceptor), fecha=fecha)
	    fal.save()

# Guarda la justificacion de las faltas
def guardarFaltas(faltas, post):
    for f in faltas:
	jus = post[str(f.id)]
	
	if jus == 'False':
	    f.justificar(False)
	elif jus == 'True':
	    f.justificar(True)
	    

# Agrega una observacion al alumno
def observar(alumno, fecha, motivo, id_preceptor):
    observacion = Observacion(descripcion=motivo, alumno=alumno, fecha=fecha, preceptor=id_preceptor)
    observacion.save()

# Agrega una amonestacion al alumno
def amonestar(alumno, fecha, motivo, cantidad, id_preceptor):
    amonestacion = Amonestacion(descripcion=motivo, alumno=alumno, fecha=fecha, cantidad=cantidad, preceptor=id_preceptor)
    amonestacion.save()

# Agrega una reincorporacion al alumno
def reincorporar(alumno):
    alumno.reincoporar()

inasistencias/templates/preceptor/alumno.html
{% extends 'base.html' %}

{% load obtenerpreceptor %}

{% block contenido %}
<div id="page-wrapper">
    <div class="row">
	<div class="col-lg-12">
	    
	    {% if cambios %}
		<div class="alert alert-success alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
		Los cambios han sido guardados con <a class="alert-link">Exito!</a>
	    </div>
	    {% endif %}
	    
	    <h1 class="page-header">{{ alumno.last_name.upper }}, {{ alumno.first_name.capitalize }}</h1>
	</div>
	<!-- /.col-lg-12 -->
    </div>
    
    <ol class="breadcrumb">
	<li><a href="{% url 'inasistencias:home' %}">Home</a></li>
	<li><a href="{% url 'inasistencias:curso' alumno.curso.id %}">Curso</a></li>
	<li class="active">Alumno</li>
    </ol>
    
    <div class="row">
	<div class="col-lg-3 col-md-6">
	    <div class="panel panel-blue">
		<a href="#faltas">
		    <div class="panel-heading">
			<div class="row">
			    <div class="col-xs-3">
				<i class=""></i>
			    </div>
			    <div class="col-xs-9 text-right">
				<div class="huge">{{ alumno.faltas }}</div>
				<div>Faltas</div>
			    </div>
			</div>
		    </div>
		    <div class="panel-footer">
			<span class="pull-left">Ver o Agregar</span>
			<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
			<div class="clearfix"></div>
		    </div>
		</a>
	    </div>
	</div>
	<div class="col-lg-3 col-md-6">
	    <div class="panel panel-green">
		<a href="#faltas">
		    <div class="panel-heading">
			<div class="row">
			    <div class="col-xs-3">
				<i class=""></i>
			    </div>
			    <div class="col-xs-9 text-right">
				<div class="huge">{{ alumno.reincorporacion }}</div>
				<div>Reincorporaciones</div>
			    </div>
			</div>
		    </div>
		    <div class="panel-footer">
			<span class="pull-left">Ver o Agregar</span>
			<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
			<div class="clearfix"></div>
		    </div>
		</a>
	    </div>
	</div>
	<div class="col-lg-3 col-md-6">
	    <div class="panel panel-yellow">
		<a href="#observaciones">
		    <div class="panel-heading">
			<div class="row">
			    <div class="col-xs-3">
				<i class=""></i>
			    </div>
			    <div class="col-xs-9 text-right">
				<div class="huge">{{ alumno.observaciones }}</div>
				<div>Observaciones</div>
			    </div>
			</div>
		    </div>
		    <div class="panel-footer">
			<span class="pull-left">Agregar y/o ver</span>
			<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
			<div class="clearfix"></div>
		    </div>
		</a>
	    </div>
	</div>
	<div class="col-lg-3 col-md-6">
	    <div class="panel panel-red">
		<a href="#amonestaciones">
		    <div class="panel-heading">
			<div class="row">
			    <div class="col-xs-3">
				<i class=""></i>
			    </div>
			    <div class="col-xs-9 text-right">
				<div class="huge">{{ alumno.amonestaciones }}</div>
				<div>Amonestaciones</div>
			    </div>
			</div>
		    </div>
		    <div class="panel-footer">
			<span class="pull-left">Agregar y/o ver</span>
			<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
			<div class="clearfix"></div>
		    </div>
		</a>
	    </div>
	</div>
    </div>
    
    <div class="row">
    
    <div class="col-lg-6">
	<div class="panel panel-default">
	    <div class="panel-heading" id="inasistencias">
		Inasistencias
	    </div>
	    <div class="panel-body">
		<form role="form" method="post">{% csrf_token %}
		    <div class="form-group">
			<p> El alumno posee hasta la fecha, <b>{{ alumno.faltas }}</b> faltas aplicadas, de las cuales <b>{{ alumno.justificadas }}</b> han sido justificadas</p><b>Justificar Inasistencias:</b>

				{% for inasistencia in alumno.vectorInasistencias %}
				    {% if inasistencia.tipo != 0 %}
				    <hr>
				    <label>{{ inasistencia.fecha }} ({{ inasistencia.cantMixto }})</label>
				    <div class="pull-right">
				    <label class="radio-inline">
					{% if inasistencia.justificado %}
					    <input type="radio" name="{{ inasistencia.id }}" value="True" checked>Justificada
					{% else %}
					    <input type="radio" name="{{ inasistencia.id }}" value="True">Justificada
					{% endif %}
				    </label>
				    <label class="radio-inline">
					{% if inasistencia.justificado %}
					    <input type="radio" name="{{ inasistencia.id }}" value="False">Injustificada
					{% else %}
					    <input type="radio" name="{{ inasistencia.id }}" value="False" checked>Injustificada
					{% endif %}
				    </label>
				    </div>
				    {% else %}
					<input type="hidden" name="{{ inasistencia.id }}">
				    {% endif %}
				{% endfor %}
			<hr>
			<button type="submit" name="guardarFaltas" class="btn btn-primary btn-block">Guardar</button>
		    </div>
		</form>
	    </div>
	</div>
	
	<div class="panel panel-default">
	    <div class="panel-heading" id="observaciones">
		Observaciones
	    </div>
	    <div class="panel-body">
		<form action="" method="post"> {% csrf_token %}
		    <label>Agregar Observacion: </label></br>
			<label>Fecha</label>
		    <div class="form-group has-success"><input class="form-control" id="fecha2" name="fechaObservacion" value="{% now 'SHORT_DATE_FORMAT' %}" required></div>
			    <label> Motivo</label>
		    <div class="form-group has-error"><input class="form-control" name="motivoObservacion" required></div>
            <input type="hidden" name="alumno" value="{{ alumno.id }}">
			<input type="hidden" name="preceptor" value="{% preceptor usuario %}">
		    <button type="submit" class="btn btn-warning btn-block">Guardar</button>
		</form></br>
		    {% for observacion in alumno.vectorObservaciones %}
		        <hr>
			<label> Fecha: </label> {{ observacion.fecha }}</br>
		        <label>Motivo: </label> {{ observacion.descripcion }}
			{% endfor %}
	    </div>
	</div>
    </div>
	    
    <div class="col-lg-6">
	<div class="panel panel-default">
	    <div class="panel-heading" id="faltas">
		Reincorporaciones
	    </div>
	    <div class="panel-body">
		<p> El alumno, ha sido reincorporado <b>{{ alumno.reincorporacion }}</b> veces.</p>
		<button class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal"> Reincorporar</button>
                            <!-- Modal -->
                            <div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content alert alert-success alert-dismissable">
                                        <div class="modal-header ">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title" id="myModalLabel">Exito</h4>
                                        </div>
                                        <div class="modal-body alert alert-success alert-dismissable">
                                            Esta seguro que desea reincorporar al alumno?
                                        </div>
                                        <div class="modal-footer">
					<form action="" method="post">{% csrf_token %}
					    <input type="hidden" name="alumnoReincorporacion" value="{{ alumno.id }}">
                                            <button type="submit" class="btn btn-success">Aceptar</button>
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
					</form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
		</form>
	    </div>
	</div>
	
	<div class="panel panel-default">
	    <div class="panel-heading" id="amonestaciones">
		Amonestaciones
	    </div>
	    <div class="panel-body">
		<form action="" method="post"> {% csrf_token %}
		    <label>Agregar Amonestaciones: </label></br>
			<label>Fecha</label>
			<div class="form-group has-success"><input class="form-control" id="fecha3" name="fechaAmonestacion" value="{% now 'SHORT_DATE_FORMAT' %}" required></div>
		    <label> Cantidad</label>
			<div class="form-group has-warning"><input class="form-control" name="cantAmonestacion" required></div>
		    <label> Motivo</label>
			<div class="form-group has-error"><input class="form-control" name="motivoAmonestacion" required></div>
            <input type="hidden" name="alumno" value="{{ alumno.id }}">
			<input type="hidden" name="preceptor" value="{% preceptor usuario %}">
		    <button type="submit" class="btn btn-danger btn-block">Guardar</button>
		</form>
        {% for amonestacion in alumno.vectorAmonestaciones %}
	            <hr><label> Fecha: </label> {{ amonestacion.fecha }}</br>
		    <label> Cantidad: </label> {{ amonestacion.cantidad }}</br>
		    <label>Motivo: </label> {{ amonestacion.descripcion }}
		{% endfor %}
	    </div>
	</div>
    </div>
    
    </div>
    
</div>
<!-- /#page-wrapper -->
{% endblock %}

inasistencias/templates/preceptor/info.html
{% extends 'base.html' %}

{% block contenido %}
<div id="page-wrapper">
    <div class="row">
	<div class="col-lg-12">
	    <h1 class="page-header">{{ curso.numero }}&ordm; {{ curso.division }} - {{ curso.anio }}</h1>
	</div>
	<!-- /.col-lg-12 -->
    </div>
    
    <ol class="breadcrumb">
	<li><a href="{% url 'inasistencias:home' %}">Home</a></li>
	{% if not usuario.is_staff %}
	    <li><a href="{% url 'inasistencias:curso' curso.id %}">Curso</a></li>
	{% endif %}
	<li class="active">Estadisticas</li>
    </ol>
    
    <div class="row">
	<div class="col-lg-12">
	    
	    {% if not curso.getVacio %}
	    <div class="panel panel-default">
		<div class="panel-heading">
		    Informacion del curso
		</div>
		<div class="panel-body">
		    <div class="row">
			<div class="col-lg-12">
			    <h3> Datos mensuales </h3>

	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-primary">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getTotalAsistenciasMensual }}</div>
			                    <div>Total de Asistencias del Curso</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-green">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getInasistenciasMensual }}</div>
			                    <div>Total de Inasistencias</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-yellow">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getAsistenciaMediaMensual }}</div>
			                    <div>Asistencia Media Total</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-red">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getPorcentajeAsistenciaMensual }}%</div>
			                    <div>Porcentaje de Asistencias</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>

		        <h3> Datos anuales </h3>
			    
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-primary">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getTotalAsistencias }}</div>
			                    <div>Total de Asistencias del Curso</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-green">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getInasistencias }}</div>
			                    <div>Total de Inasistencias</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-yellow">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getAsistenciaMedia }}</div>
			                    <div>Asistencia Media Total</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
	                <div class="col-lg-3 col-md-6">
	                    <div class="panel panel-red">
		                <div class="panel-heading">
		                    <div class="row">
			                <div class="col-xs-3">
			                    <i class=""></i>
			                </div>
			                <div class="col-xs-9 text-right">
			                    <div class="huge">{{ curso.getPorcentajeAsistencia }}%</div>
			                    <div>Porcentaje de Asistencias</div>
			                </div>
		                    </div>
		                </div>
	                    </div>
	                </div>
			</div>
		    </div>
		</div>
	    </div>
	    {% endif %}
	    
	    <div class="panel panel-default">
		<div class="panel-heading">
		    Lista de alumnos
		</div>
		<div class="panel-body">
		    <div class="row">
			<div class="col-lg-12">
			    <div class="table-responsive">
				<table id="tabla" class="display" cellspacing="0" width="100%">
				    <thead>
					<tr>
					  <th>APELLIDO, Nombre</th>
					  <th>DNI</th>
					  <th>Email</th>
					</tr>
				    </thead>
				    <tbody>
					
				    {% for alumno in curso.alumno_set.all %}
					<tr>
					    <td id="editable">{% if not usuario.is_staff %}<a href="{% url 'inasistencias:alumno' alumno.id %}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>{% endif %} {{ alumno.last_name.upper }}, {{ alumno.first_name.capitalize }}</td>
					    <td id="editable">{{ alumno.dni }}</td>
					    <td id="editable"><a href="mailto:{{ alumno.email }}">{{ alumno.email }}</a></td>
					</tr>
				    {% endfor %}
				      
				    </tbody>
				</table>
				
				{% if usuario.is_staff %}
				    <form role="form" method="post">{% csrf_token %}
				      <br />
				      <button type="submit" name="editar" class="btn btn-primary">Editar</button>
				      <button type="submit" name="pasar" class="btn btn-danger">Pasar de a&ntilde;o</button>
				    </form>
				{% endif %}
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>


{% endblock %}

inasistencias/templates/preceptor/preceptor.html
{% extends 'base.html' %}

{% block contenido %}
<div id="page-wrapper">
    <div class="row">
	<div class="col-lg-12">
	    <h1 class="page-header">Cursos</h1>
	</div>
	<!-- /.col-lg-12 -->
    </div>
    
    <div class="row">
	
	{% for curso in cursos %}
	
	<div class="col-lg-3 col-md-6">
	    <div class="panel panel-{{ curso.color }}">
	    
		<a href="{% url 'inasistencias:curso' curso.id %}">
		<div class="panel-heading">
		    <div class="row">
			<div class="col-xs-3">
			    <i class=""></i>
			</div>
			<div class="col-xs-9 text-right">
			    <div class="huge">{{ curso.numero }}&ordm; {{ curso.division }}</div>
			    <div>{{ curso.anio }}</div>
			</div>
		    </div>
		</div>
		<div class="panel-footer">
		    <span class="pull-left">Entrar al curso</span>
		    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
		    <div class="clearfix"></div>
		</div>
		</a>
	    </div>
	</div>
	    
	    
	{% endfor %}
	
    </div>
</div>
{% endblock %}