RDFvevo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^', include('inasistencias.urls', namespace = "inasistencias")),
    url(r'^admin/', include(admin.site.urls)),
)

inasistencias/urls.py
from django.conf.urls import patterns, include, url
from RDFvevo import settings

urlpatterns = patterns('',

    url(r'^$', 'inasistencias.views.home', name='home'),
    url(r'^loguearse/$', 'inasistencias.views.loguearse', name='loguearse'),
    url(r'^desloguearse/$', 'inasistencias.views.desloguearse', name='desloguearse'),
    url(r'^curso/(?P<id_curso>\d+)/$', 'inasistencias.views.curso', name='curso'),
    url(r'^curso/(?P<id_curso>\d+)/info/$', 'inasistencias.views.info', name='info'),
    url(r'^alumno/(?P<id_alumno>\d+)/$', 'inasistencias.views.alumno', name='alumno'),
    
)

inasistencias/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext
from django.template.defaulttags import NowNode
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.decorators import login_required

from inasistencias.templatetags.faltas import formatear_fecha
from inasistencias.models import Curso, Preceptor, Alumno, Curso, Inasistencia, Observacion, Amonestacion


@login_required(login_url="/loguearse")
def home(request):
    context = RequestContext(request)
    
    # Si es Administrador
    if request.user.is_staff:

	if request.method == 'POST':
	    print request.POST
	    
	    if 'infoCurso' in request.POST:
		curso = request.POST['cursos']
		print Curso.objects.filter(id=curso)
		
		return HttpResponseRedirect(reverse('inasistencias:info', args=(int(curso), ) ))
	      
	    elif 'nuevoCurso' in request.POST:
		return HttpResponseRedirect('admin/inasistencias/curso/add/')
		
	    elif 'verPreceptor' in request.POST:
		preceptor = request.POST['preceptores']
		return HttpResponseRedirect('admin/inasistencias/preceptor/' + preceptor + '/')
		
	    elif 'nuevoPreceptor' in request.POST:
		return HttpResponseRedirect('admin/inasistencias/preceptor/add/')
	      
	return render_to_response('admin/administrador.html', {'usuario': request.user, 'cursos': Curso.objects.all(), 'preceptores': Preceptor.objects.all()}, context)
	
    
    # Si es Preceptor
    elif es_preceptor(request.user):
	return render_to_response('preceptor/preceptor.html', {'usuario': request.user, 'cursos': Curso.objects.all().filter(preceptor=request.user)}, context)
    
    # Si es Alumno
    elif es_alumno(request.user):
	return render_to_response('alumno/alumno.html', {'usuario': request.user, 'alumno': Alumno.objects.get(pk=request.user.pk) }, context)
    
    # Sino
    else:
	return HttpResponse('ERROR')

def loguearse(request):
    context = RequestContext(request)
	
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
	# Usuario y contrasena
	username = request.POST['username']
	password = request.POST['password']

	user = authenticate(username=username, password=password)

	if user:
	    # Is the account active? It could have been disabled.
	    if user.is_active:
		# If the account is valid and active, we can log the user in.
		# We'll send the user back to the homepage.
		login(request, user)

		return redirect('/')

	    else:
		# An inactive account was used - no logging in!
		return HttpResponse("ERROR: cuenta inactiva.")
	else:
	    # Bad login details were provided. So we can't log the user in.
	    print "Invalid login details: {0}, {1}".format(username, password)
	    return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
	# No context variables to pass to the template system, hence the
	# blank dictionary object...
	
	return render_to_response('login.html', context)

def desloguearse(request):
    logout(request)
    
    return redirect('/loguearse')

@login_required(login_url="/loguearse")
def curso(request, id_curso):
    fecha = NowNode("SHORT_DATE_FORMAT").render(None)
    alumnos = Alumno.objects.all().filter(curso_id=id_curso)
    cambios = False
    
    if request.method == 'POST':
	
	if request.POST.get('cargar'):
	    fecha = request.POST['fecha']
	
	if request.POST.get('guardar'):
	    fecha = request.POST['fecha']
	    preceptor = request.POST['preceptor']
	    
	    registrar_faltas(fecha, alumnos, request.POST, preceptor)
	    cambios = True
		
    
    # Si es preceptor
    if es_preceptor(request.user):
	return render_to_response('preceptor/curso.html', {'usuario': request.user, 'cambios':cambios, 'alumnos': alumnos, 'curso': Curso.objects.get(id=id_curso), 'dia': fecha}, RequestContext(request))

    # Sino
    else:
	return HttpResponse('Necesitas estar logueado como preceptor para ver esto...')

@login_required(login_url="/loguearse")
def alumno(request, id_alumno):
    faltas = Inasistencia.objects.all().filter(alumno_id=id_alumno)
    cambios = False
    
    # Si es preceptor
    if es_preceptor(request.user):
      
	# Si se ha recibido una peticion "POST"
        if request.method == 'POST':
	    print request.POST
	    
	    # Si es una peticion de "Guardar faltas"    
            if 'guardarFaltas' in request.POST:
		guardarFaltas(faltas, request.POST)
		cambios = True

            # Si es una peticion de "Crear Observacion"    
            if request.POST.get('motivoObservacion'):
                fecha = request.POST.get('fechaObservacion')
                fecha2 = formatear_fecha(fecha)
                motivo = request.POST['motivoObservacion']
                alumno = Alumno.objects.get(id=id_alumno)
                preceptor = request.POST['preceptor']
                preceptor = Preceptor.objects.get(id=preceptor)
                observar(alumno, fecha2, motivo, preceptor)
                cambios = True

            # Si es una peticion de "Crear Amonestacion"
            if request.POST.get('motivoAmonestacion'):
		print request.POST
                fecha = request.POST.get('fechaAmonestacion')
                fecha2 = formatear_fecha(fecha)
                motivo = request.POST['motivoAmonestacion']
                cantidad = request.POST['cantAmonestacion']
                alumno = Alumno.objects.get(id=id_alumno)
                preceptor = request.POST['preceptor']
                preceptor = Preceptor.objects.get(id=preceptor)
                amonestar(alumno, fecha2, motivo, cantidad, preceptor)
                cambios = True

            # Si es una peticion de "Reincorporar"
            if request.POST.get('alumnoReincorporacion'):
                alumno = Alumno.objects.get(id=id_alumno)
                reincorporar(alumno)
                cambios = True
	
	return render_to_response('preceptor/alumno.html', {'usuario': request.user, 'cambios': cambios, 'alumno': Alumno.objects.get(id=id_alumno)}, RequestContext(request))

    # Sino
    else:
	return HttpResponse('Necesitas estar logueado como preceptor para ver esto...')

@login_required(login_url="/loguearse")
def info(request, id_curso):
    print request.POST
    # Si es preceptor o administrador
    if es_preceptor(request.user) or request.user.is_staff:
	return render_to_response('preceptor/info.html', {'usuario': request.user, 'curso': Curso.objects.get(id=id_curso)}, RequestContext(request))

    # Sino
    else:
	return HttpResponse('Necesitas estar logueado como preceptor para ver esto...')


# Devuelve true si es preceptor
def es_preceptor(usuario):
    try:
	Preceptor.objects.get(pk=usuario.pk)
	return True
    except:
	return False

# Devuelve true si es alumno
def es_alumno(usuario):
    try:
	Alumno.objects.get(pk=usuario.pk)
	return True
    except:
	return False

# Leva a cabo el registro de faltas de una lista de alumnos
def registrar_faltas(fecha, alumnos, post, preceptor):
    fecha = formatear_fecha(fecha)
    dic = {
      'P': 0,
      '1/2': 0.5,
      '1/4': 0.25,
      '3/4': 0.75,
      'A': 1,
    }

    for al in alumnos:
	falta = Inasistencia.objects.filter(alumno=al).filter(fecha=fecha)
	# Tipo de inasistencia
	tipo = post[str(al.id)]
	
	# Si existe una falta de ese alumno en esa fecha
	if falta:
	    # Si no coincide
	    if dic[tipo] != falta[0].tipo:
		falta[0].tipo = dic[tipo]
		falta[0].save()
	
	# Si no existe una falta de ese alumno en esa fecha se crea
	else:
	    fal = Inasistencia(tipo=dic[tipo], alumno=al, preceptor=Preceptor.objects.get(username=preceptor), fecha=fecha)
	    fal.save()

# Guarda la justificacion de las faltas
def guardarFaltas(faltas, post):
    for f in faltas:
	jus = post[str(f.id)]
	
	if jus == 'False':
	    f.justificar(False)
	elif jus == 'True':
	    f.justificar(True)
	    

# Agrega una observacion al alumno
def observar(alumno, fecha, motivo, id_preceptor):
    observacion = Observacion(descripcion=motivo, alumno=alumno, fecha=fecha, preceptor=id_preceptor)
    observacion.save()

# Agrega una amonestacion al alumno
def amonestar(alumno, fecha, motivo, cantidad, id_preceptor):
    amonestacion = Amonestacion(descripcion=motivo, alumno=alumno, fecha=fecha, cantidad=cantidad, preceptor=id_preceptor)
    amonestacion.save()

# Agrega una reincorporacion al alumno
def reincorporar(alumno):
    alumno.reincoporar()

inasistencias/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RDFvevo</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{STATIC_URL}}css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{STATIC_URL}}css/sb-admin-2.css" rel="stylesheet">
    
    <!-- Tema JQuery CSS -->
    <link href="{{STATIC_URL}}css/overcast/jquery-ui.css" rel="stylesheet">

    <!-- Nuestro CSS -->
    <link href="{{STATIC_URL}}paneles.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{STATIC_URL}}font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    <link href="{{STATIC_URL}}css/jquery.dataTables.min.css" rel="stylesheet">
    
</head>

<body>

    <div id="wrapper">

	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
	    <div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		    <span class="sr-only"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">{{ usuario.username.capitalize }}</a>
	    </div>
	    <!-- /.navbar-header -->

	    <div class="navbar-default sidebar" role="navigation">
		<div class="sidebar-nav navbar-collapse">
		    <ul class="nav" id="side-menu">
			<li>
			    <a href="{% url 'inasistencias:home' %}"><i class="fa fa-dashboard fa-fw"></i> Inicio</a>
			</li>
			<li>
			    <a href="{% url 'inasistencias:desloguearse' %}"><i class="fa fa-sign-out fa-fw"></i>Salir</a>
			</li>
		    </ul>
		</div>
	    </div>
	</nav>
    
    {% block contenido %}{% endblock %}
    
    </div>
    
    <!-- jQuery Version 1.11.0 -->
    <script src="{{STATIC_URL}}js/jquery-1.11.0.js"></script>
    
    <!-- jQueryUi Version 1.8 -->
    <script src="{{STATIC_URL}}js/jquery-ui.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{STATIC_URL}}js/plugins/metisMenu/metisMenu.min.js"></script>
    
    <script src="{{STATIC_URL}}js/jquery.dataTables.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{STATIC_URL}}js/sb-admin-2.js"></script>
    
    <script type="text/javascript">
	$('input[type="date"]').prop('type','text');
	$.datepicker.regional['es'] = {
	    closeText: 'Cerrar',
	    prevText: '<Ant',
	    nextText: 'Sig>',
	    currentText: 'Hoy',
	    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
	    monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
	    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
	    dayNamesShort: ['Dom','Lun','Mar','Mie','Juv','Vie','Sab'],
	    dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sa'],
	    weekHeader: 'Sm',
	    dateFormat: 'dd/mm/yy',
	    firstDay: 1,
	    maxDate: '0',
	    beforeShowDay: $.datepicker.noWeekends,
	    isRTL: false,
	    showMonthAfterYear: false,
	    yearSuffix: ''
	};
	
	$.datepicker.setDefaults($.datepicker.regional['es']);
	
	$(function () {
	    $("#fecha").datepicker();
	    $("#fecha2").datepicker();
	    $("#fecha3").datepicker();
	});
	
	// Tabla de alumnos
	$(document).ready(function() {
	    $('#tabla').dataTable( {
		"bPaginate": false,
		"bInfo": false,
		"oLanguage": {
		    "sSearch": "Filtrar:",
		},
	    } );
	} );
    </script>
</body>

</html>

inasistencias/templates/login.html
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RDFvevo</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{STATIC_URL}}css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{STATIC_URL}}css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{STATIC_URL}}font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>

<body>
    <div class="container">
	<div class="row">
	    <div class="col-md-4 col-md-offset-4">
		<div class="login-panel panel panel-default">
		    <div class="panel-heading">
			<h3 class="panel-title">Loguearse</h3>
		    </div>
		    <div class="panel-body">
			<form action="" role="form" method="POST">{% csrf_token %}
			    <fieldset>
				<div class="form-group">
				    <input class="form-control" placeholder="Usuario" name="username" type="username" required autofocus>
				</div>
				<div class="form-group">
				    <input class="form-control" placeholder="Contrase&ntilde;a" name="password" type="password" required>
				</div>
				
				<!-- Change this to a button or input when using this as a form -->
				<input class="btn btn-lg btn-success btn-block" type="submit" value="Ingresar">
			    </fieldset>
			</form>
		    </div>
		</div>
	    </div>
	</div>
    </div>

    <!-- jQuery Version 1.11.0 -->
    <script src="{{STATIC_URL}}js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{STATIC_URL}}js/plugins/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{STATIC_URL}}js/sb-admin-2.js"></script>

</body>